# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "spezi-study-platform-server"
main = "src/index.ts"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]
preview_urls = false


[observability]
enabled = true

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "spezi-study-platform-server-db"
database_id = "10e8fe07-504a-4c32-8892-ff2d50f9a028"
migrations_dir = "drizzle"

[[kv_namespaces]]
binding = "KV"
id = "4cea1599274c47a1b390d5a5f3ba45af"


# To protect the database id, we ignore this
# file when committing to the repo by running once:
# git update-index --assume-unchanged wrangler.toml
#
# Put back in git if you need to commit this file:
# git update-index --no-assume-unchanged wrangler.toml